name: Cloud Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java Environment
        # Modernized from v4 to v5 to remove the deprecation warning
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up NodeJS Engine
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install and Build App File
        working-directory: "Web Apps/Timer App"
        run: |
          npm install
          npx capacitor sync
          cd android
          ./gradlew assembleDebug

      - name: Upload APK Asset to Actions Timeline
        uses: actions/upload-artifact@v4
        with:
          name: Timer App
          path: "Web Apps/Timer App/android/app/build/outputs/apk/debug/app-debug.apk"